class ErrorCode:
    FILE_SCOPE_VIOLATION = "FILE_SCOPE_VIOLATION"
    ACTION_TYPE_VIOLATION = "ACTION_TYPE_VIOLATION"
    EMPTY_DIFF_NOT_ALLOWED = "EMPTY_DIFF_NOT_ALLOWED"
    CONTEXT_MISMATCH = "CONTEXT_MISMATCH"
